SILENCE_INDEX = 0

MEASURES = 4
MEASURE_LENGTH = 16
SEQUENCE_LENGTH = MEASURES * MEASURE_LENGTH # Four measure of 16 notes segments

BATCH_LOG_INTERVAL = 50
VALID_PREDICTION_SAMPLE_RATE = 10 
OPTIMIZER_ADAM_LR = 1.0
EPOCHS = 180
BATCH_SIZE = 8
SHUFFLE_DATA = True