SEGMENTS_PER_BEAT = 4
BEAT_SEGMENT_ACCEPTED_ROUNDING_ERROR = 1/50

MIDI_NOTE_COUNT = 128
MIDI_NOTE_AND_SILENCE_COUNT = MIDI_NOTE_COUNT + 1
ALL_POSSIBLE_INPUTS_COUNT = MIDI_NOTE_AND_SILENCE_COUNT + 1

BOTTOM_SKIPPING_INDEX = 0
TOP_SKIPPING_INDEX = 128
ALL_POSSIBLE_INPUT_BOTTOM_TOP_CHOPPED = ALL_POSSIBLE_INPUTS_COUNT - \
    ((MIDI_NOTE_COUNT - TOP_SKIPPING_INDEX) + BOTTOM_SKIPPING_INDEX)

ALL_NOTE_INPUT_VECTOR_SIZE = ALL_POSSIBLE_INPUT_BOTTOM_TOP_CHOPPED + SEGMENTS_PER_BEAT

CONTINUE_NOTE_INDEX = 1
SILENCE_INDEX = 0

# Do about 4 measures of 4/4 for window slide.
WINDOW_SLIDE_SIZE = 8
PREDICTION_SIZE = 4
